# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JHAPP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('coming_from', models.TextField()),
                ('nationality', models.TextField()),
                ('degree', models.TextField()),
                ('graduation', models.DateField()),
                ('major', models.TextField()),
                ('university', models.TextField()),
                ('_18yo', models.BooleanField()),
                ('needs_reimbursement', models.BooleanField()),
                ('needs_visa', models.BooleanField()),
                ('github', models.TextField()),
                ('devpost', models.TextField()),
                ('linkedin', models.TextField()),
                ('personal_site', models.TextField()),
                ('first_hackathon', models.BooleanField()),
                ('why_jacobshack', models.TextField()),
                ('previous_projects', models.TextField()),
                ('tshirt_size', models.TextField()),
                ('dietary_requirements', models.TextField()),
                ('has_team', models.BooleanField()),
                ('names_of_teammates', models.TextField()),
                ('cv', models.FileField(upload_to='')),
                ('agree_to_policy', models.TextField()),
                ('agree_to_coc', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('sentmail', models.BooleanField(default=False)),
            ],
        ),
    ]
