# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_viz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhapp',
            name='_18yo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='cv',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='first_hackathon',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='graduation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='has_team',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='needs_reimbursement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='needs_visa',
            field=models.TextField(),
        ),
    ]
