# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_viz', '0003_auto_20160918_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhapp',
            name='agree_to_coc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='agree_to_policy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='cv',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='devpost',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='dietary_requirements',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='github',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='last_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='linkedin',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='names_of_teammates',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='jhapp',
            name='personal_site',
            field=models.TextField(null=True),
        ),
    ]
