# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_viz', '0005_auto_20160918_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhapp',
            name='why_jacobshack',
            field=models.TextField(blank=True, null=True),
        ),
    ]
