# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 07:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_viz', '0006_auto_20160918_2233'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='jhapp',
            managers=[
                ('apps', django.db.models.manager.Manager()),
            ],
        ),
    ]
