# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('typeform_viz', '0007_auto_20160919_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jhapp',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
